version: 0.0
os: linux
files:
   - source: /
     destination: /var/www/test
permissions:
   - object: /var/www/test
     pattern: "**"
     owner: root
     group: root
     mode: 755
     type:
       - file
hooks:
 AfterInstall:
   - location: sh /home/ubuntu/Reload.sh
     runas: root